# Generated by Django 4.2.7 on 2025-03-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cartorderitem_coupons_cartorderitem_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('New Order', 'New Order'), ('New Review', 'New Review'), ('New Course Question', 'New Course Question'), ('Course Published', 'Course Published'), ('Course Enrollment Completed', 'Course Enrollment Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3'), ('4', '4 Star'), ('5', '5 Star')], default=None),
        ),
    ]
